"""
Configurazioni di rete per comunicazione Python-C++.
"""

HOST = "127.0.0.1"
PORT = 5001

SOCKET_TIMEOUT = 30
CONNECT_TIMEOUT = 5

WS_PING_INTERVAL = 20
WS_PING_TIMEOUT = 20
WS_RECONNECT_DELAY = 1.0
WS_MAX_RECONNECT_DELAY = 30.0
